[package]
edition = "2018"
name = "criterion-issue-269"
version = "0.1.0"

[[bench]]
name = "benches"
path = "benches/benches.rs"
harness = false

[dev-dependencies]
criterion = "=0.2.10"

[lib]
path = "src/lib.rs"
bench = false
